# Generated by Django 5.0.6 on 2024-06-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_blogpost_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'managed': True, 'verbose_name': 'Posts_table', 'verbose_name_plural': 'ModelNames'},
        ),
    ]
