# Generated by Django 5.0.6 on 2024-06-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'managed': True, 'verbose_name': 'Posts_table', 'verbose_name_plural': 'Posts_table'},
        ),
    ]
